- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  register: key_added
  until: key_added is not failed
  retries: 2
  delay: 10

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
    filename: docker
    mode: 0600
    validate_certs: no 
  ignore_errors: yes

- name: Install Docker
  apt: 
    name:
      - docker-ce
      - docker-ce-cli
    state: present

